FROM node:lts-alpine AS builder
WORKDIR /usr/src/api
COPY package.json ./
RUN yarn install --network-timeout 1000000000
COPY . .
ENV NODE_ENV homolog
RUN yarn migrate:homolog
RUN yarn build

FROM node:lts-alpine AS api-release
WORKDIR /usr/src/api
COPY package.json ./
RUN yarn install --prod --network-timeout 1000000000 
ENV NODE_ENV homolog 
COPY --from=builder /usr/src/api/dist ./
COPY --from=builder /usr/src/api/env/homolog.env ./env/homolog.env
EXPOSE 4000
CMD [ "yarn", "start:prod" ]