FROM node:lts-alpine AS builder
WORKDIR /usr/src/api
COPY package.json ./
RUN yarn install --network-timeout 1000000000
COPY . .
ENV NODE_ENV staging
RUN yarn migrate:stage
RUN yarn build

FROM node:lts-alpine AS api-stage
WORKDIR /usr/src/api
COPY package.json ./
RUN yarn install --prod --network-timeout 1000000000 
ENV NODE_ENV staging 
COPY --from=builder /usr/src/api/dist ./
COPY --from=builder /usr/src/api/env/staging.env ./env/staging.env
EXPOSE 4000
CMD [ "yarn", "start:prod" ]